apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: syncthing
  name: syncthing
  namespace: syncthing
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
