apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monerod
  namespace: monerod
spec:
  encryptedData: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monerod
    type: Opaque
