apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/name: monerod
  name: monerod
  namespace: monerod
spec:
  encryptedData:
    RPC_PASSWD: AgBJORYd2z40WEP2uVK5gsJGlYJeR3dMEtOV1DxjafuoBu38SUcEe8uQSVZZDuya/M76lhFv3EmOJ63M22Y6tGVKamDrIiCzeQB0ub3t5IAyGwYWYxaz2sHVT9R5CvE3GJNLL/tnPWmG67UsHDvL/iZAJKLqBDmKO7WJacj7WUvTsLmzM5x1m6Wwlm3f1fJXNSgVIyhaFB9nrG+FrNJ2MipDC7aVBH/RtIOP2RuDoXLcJaq6JVm4FxX+dgVZJ3CIM0XomKFRmmshR8cx9p8OjdlMG6NkX+UZvzRdiHY+JbP4Angqk0KcyJ55mSrPIk7YV/lIGf/QFpLI0voOv/sBaBZFq65GfKsL+ZaRm5ZdVChh452uuvKGp3zlyFNS3BuXgBGVc4pcqevYjxeJ9IpresufMfUDvhuURbGiweptcxZio88V5NZtEN7bQaefv51XvF9bi7fAIsq29LtWGhMpSL+SVu3U4FEJJKmYfE8+88+dIwdIen4mrqBoxh4TyLrkyWM2X2QKTa0V3xn6E9gDHIw04bHJEJNzjPT2grK2XD+Rc4uBryjEe/v7zFnttGQ7FkUheOpDkaLiMTAZyUxy01MJd8ThGZfSswa7zg5SktvnO7OW+AbQmjks50TVtXL4tx9p8mG4Ul5KGCp7jlaCLW1W43i1+2Zq7xcU9RByr6phnKLaYDUxL0jny8JcReA54CA216x92BDoEvivJ+pGbbftMA==
    RPC_USER: AgB6gnNBZNfVYgipblSeK1dgUV2BQxu0fPUzfOjr+5YQNFDHLoRGReSC5L4eSl+Smr/Rw1RaDXIq1bWcjhr9LzL/1gOxD5sVqZuvLa5zqfFhNbG6zI7iwZLp3LEJ0vr85nEg9Bnj6dotHx2eoqKpMpfCMxE1yb0F+eS5rPAM7EgSzj27imAqSX3HuViLUxZZIiq6mTjSSPMncDYTuHTZpbEzcbNMRe2hDRwk5llDdKiJ2xtSc+urRGwzXGrvPkuRIv/41yboB9D+wROPtjH0HIRdv2NbeghIvFCr5dtHHpZkkU1trfvtJ0yWoD4urybVai/cj1Wrn3hGPlmQUXYJGiOdV3KgerNHpgTWPxRB1jP5jCObYeK9Dyo1aPLwW6DFXtEvkPbzVtm+N/gqqWy4xvV6QXvzAoEpPka1/teTujOPIBAfGG6nM/BLvY1IyCd2LaHUbrfHXMT1tkOlixgY1W8uLCcs6FAsHVWZM3JxyrM/rfSYW0u/KXtIjJ2lzl1Io4lr5t9nAZan6WNFkw11TzhA6NFF/opXQJMDCZUceaPDNclvZzw81+LlboxhKwzPXi1+lAh+RPM+5e17VR+RsMj+tQK3V+lQiXd0yOQB/yhy8+DfoKAnBy9VhiKKpxdDaFkZm8BtlnFdaH3sCRvJVApjZZ7zJht2n3EInVIG9O+zEcFNX607vKusLqgCGGEfGdJbE0rzGuLRrTAluhvlKfY=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monerod
    type: Opaque
