apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nfs-server
  name: nfs-server
  namespace: default
spec:
  clusterIP: 10.43.217.217
  ports:
  - name: http
    port: 2049
    protocol: TCP
  selector:
    app.kubernetes.io/name: nfs-server
  type: LoadBalancer
