apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: plex-nfs
  name: plex-nfs
  namespace: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-nfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex-nfs
    spec:
      containers:
      - env:
        - name: SHARED_DIRECTORY
          value: /share
        image: shimmerjs/nfs-alpine-server:amd
        imagePullPolicy: Always
        name: plex-nfs
        ports:
        - containerPort: 2049
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - SETPCAP
            - SYS_RESOURCE
            - DAC_READ_SEARCH
        volumeMounts:
        - mountPath: /share
          name: host-path
      nodeSelector:
        k3s.io/hostname: bookman
      volumes:
      - hostPath:
          path: /media
          type: Directory
        name: host-path
