apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart: https://kubernetes-charts.storage.googleapis.com/nextcloud-1.9.1.tgz
  valuesContent: |
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enabled: "true"
      tls:
      - hosts:
        - nextcloud.liveworkloft.dev
        secretName: nextcloud-ingress
    nextcloud:
      host: nextcloud.liveworkloft.dev
    persistence:
      enabled: "true"
      size: 500Gi
      storageClass: local-path
