apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tautulli
  name: tautulli
  namespace: default
spec:
  ports:
  - name: http
    port: 8181
    protocol: TCP
  selector:
    app.kubernetes.io/name: tautulli
